package LibraryServer;


/**
* LibraryServer/ServerFeatures.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerFeaturesInterface.idl
* Thursday, March 7, 2019 at 1:25:45 AM Eastern Standard Time
*/

public interface ServerFeatures extends ServerFeaturesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerFeatures
