package LibraryServer;


/**
* LibraryServer/ServerFeaturesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerFeaturesInterface.idl
* Thursday, March 7, 2019 at 1:25:44 AM Eastern Standard Time
*/

public abstract class ServerFeaturesPOA extends org.omg.PortableServer.Servant
 implements LibraryServer.ServerFeaturesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("findItem", new java.lang.Integer (0));
    _methods.put ("listAvailability", new java.lang.Integer (1));
    _methods.put ("returnItem", new java.lang.Integer (2));
    _methods.put ("borrowItem", new java.lang.Integer (3));
    _methods.put ("addItem", new java.lang.Integer (4));
    _methods.put ("removeItem", new java.lang.Integer (5));
    _methods.put ("createUser", new java.lang.Integer (6));
    _methods.put ("createManager", new java.lang.Integer (7));
    _methods.put ("addToQueue", new java.lang.Integer (8));
    _methods.put ("validateClient", new java.lang.Integer (9));
    _methods.put ("exchangeItem", new java.lang.Integer (10));
    _methods.put ("shutdown", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // LibraryServer/ServerFeatures/findItem
       {
         String userID = in.read_string ();
         String itemName = in.read_string ();
         String $result = null;
         $result = this.findItem (userID, itemName);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // LibraryServer/ServerFeatures/listAvailability
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listAvailability (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // LibraryServer/ServerFeatures/returnItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         String $result = null;
         $result = this.returnItem (userID, itemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // LibraryServer/ServerFeatures/borrowItem
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         int numberOfDays = in.read_long ();
         String $result = null;
         $result = this.borrowItem (userID, itemID, numberOfDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // LibraryServer/ServerFeatures/addItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         String itemName = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.addItem (managerID, itemID, itemName, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // LibraryServer/ServerFeatures/removeItem
       {
         String managerID = in.read_string ();
         String itemID = in.read_string ();
         int quantity = in.read_long ();
         String $result = null;
         $result = this.removeItem (managerID, itemID, quantity);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // LibraryServer/ServerFeatures/createUser
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.createUser (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // LibraryServer/ServerFeatures/createManager
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.createManager (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // LibraryServer/ServerFeatures/addToQueue
       {
         String userID = in.read_string ();
         String itemID = in.read_string ();
         int numberOfDays = in.read_long ();
         String $result = null;
         $result = this.addToQueue (userID, itemID, numberOfDays);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // LibraryServer/ServerFeatures/validateClient
       {
         String clientID = in.read_string ();
         String $result = null;
         $result = this.validateClient (clientID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // LibraryServer/ServerFeatures/exchangeItem
       {
         String userID = in.read_string ();
         String newItemID = in.read_string ();
         String oldItemID = in.read_string ();
         String $result = null;
         $result = this.exchangeItem (userID, newItemID, oldItemID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // LibraryServer/ServerFeatures/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:LibraryServer/ServerFeatures:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ServerFeatures _this() 
  {
    return ServerFeaturesHelper.narrow(
    super._this_object());
  }

  public ServerFeatures _this(org.omg.CORBA.ORB orb) 
  {
    return ServerFeaturesHelper.narrow(
    super._this_object(orb));
  }


} // class ServerFeaturesPOA
