package LibraryServer;


/**
* LibraryServer/ServerFeaturesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerFeaturesInterface.idl
* Thursday, March 7, 2019 at 1:25:45 AM Eastern Standard Time
*/

public interface ServerFeaturesOperations 
{
  String findItem (String userID, String itemName);
  String listAvailability (String managerID);
  String returnItem (String userID, String itemID);
  String borrowItem (String userID, String itemID, int numberOfDays);
  String addItem (String managerID, String itemID, String itemName, int quantity);
  String removeItem (String managerID, String itemID, int quantity);
  String createUser (String managerID);
  String createManager (String managerID);
  String addToQueue (String userID, String itemID, int numberOfDays);
  String validateClient (String clientID);
  String exchangeItem (String userID, String newItemID, String oldItemID);
  void shutdown ();
} // interface ServerFeaturesOperations
